### ISSUE TITLE
Android build fails on RN 0.65 after updating toolbar-android to 0.2.0

### ISSUE THREAD

**Issue by tcp-ameza** [react-native-toolbar-android/toolbar-android#56]
Issue

> Task :react-native-community_toolbar-android:compileDebugJavaWithJavac FAILED

After updating React Native from 64.1 to 65.1, android build fails with the error below:

```
node_modules/@react-native-community/toolbar-android/android/src/main/java/com/reactnativecommunity/toolbarandroid/ReactToolbar.java:133: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-community_toolbar-android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

I updated toolbar-android to 0.2.0 since the previous version was causing issues as well.

As a current workaround, I removed the @ Override above the getExtras() method (that's where the issue is pointing at). Doing this fixes my issue and my app works without a problem. Not sure if it an issue with my environment or if anyone has had this issue before.

**Comment by connectdotz** [comment]
Chances are you have an outdated fresco dependency... but the workaround you proposed is a good one to make the library backward compatible regardless, I will incorporate it, thanks!

**Comment by tcp-ameza** [comment]
Yeah, I think that's what it was. I am able to build my app without a problem now! Thanks for looking into this.
